# NIE UZYWAMY TAGA LATEST
FROM alpine:latest 

# Install dependecies
RUN apk add --no-cache \
        bash \
        vim \
        curl \
        util-linux \
        openrc \
        net-tools \
        ca-certificates \
        libsasl \
        mailx \
        postfix \
        runit \
        bind-tools \
        postfix-policyd-spf-perl

# Copy config
COPY main.cf /etc/postfix/

# Forward logs to docker log collector
#RUN ln -sf /dev/stdout /var/log/postfix.log

# Define port
EXPOSE 25/tcp

# Start command
CMD /usr/sbin/postfix start-fg

